### ISSUE TITLE
cut a new release?

### ISSUE THREAD

**Issue by dreyks** [gsamokovarov/rvt#1]
Hey! Can you cut a new release? Stable cannot be used with Rails5 because of '~> 4.0' activemodel requirement.

I can use master, but I try to minimize github gem usage

Thanks!

**Comment by gsamokovarov** [comment]
Hey!

Sorry, I have been neglecting this for a while. Give me a bit of time over the weekend, and I'll try to cut it out. There is some work done already, but it's still not finished. ✌️

**Comment by dreyks** [comment]
that's ok :) if any help needed i'd be glad to dive in

**Comment by gsamokovarov** [comment]
@dreyks I have release `1.0.0` you may try it out and see if it works for you. 🍻

**Comment by dreyks** [comment]
yup, this works. Thanks!
