### ISSUE TITLE
ReferenceError: Can't find variable: config

### ISSUE THREAD

**Issue by drale2k** [gsamokovarov/rvt#2]
Hi,

 i get the following error in a Rails 5.2 installation.

`ReferenceError: Can't find variable: config` in console_sessions.js line 142 `config.terminal.cols = geometry[0];`

**Comment by drale2k** [comment]
I fixed this by switching to the xtermjs branch but i am now running into a new issue. Will open a new issue,

**Comment by gsamokovarov** [comment]
Oh, I have to finish the `xtermjs` branch and put out a new release. Let me test it for a bit because it's been a while since I have worked on it.

**Comment by drale2k** [comment]
Sure, just to be clear, the mentioned issue occurred on the master and not on xtermjs branch.
